apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: kubernetes-node-app
  region: us-west-2
  

managedNodeGroups:
  - name: eks-ng
    minSize: 2
    maxSize: 4
    desiredCapacity: 3
    instanceType: "t3.medium"
    volumeSize: 5
    privateNetworking: true
    spot: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub   
    labels: {env: dev}
    tags:
      costid: devops
    iam:
      withAddonPolicies:
        externalDNS: true
        autoScaler: true
        ebs: true
        efs: true
        cloudWatch: true
        albIngress: true