---
apiVersion: v1
kind: Service
metadata:
    name: kubernetes-node-app
    namespace: development
    labels:
        app: kubernetes-node-app
spec:
    type: LoadBalancer
    selector:
        app: kubernetes-node-app
    ports:
    - port: 80
      protocol: TCP  
      targetPort: 3000

